language: cpp

matrix:
  include:
    # Ubuntu Trusty beta build environment. Trusty has CMake 2.8.12, which we
    # need to build gtest.
    #
    # NOTE: Per [1], the official way to opt in to Trusty is to set
    # `sudo: required` and `dist: trusty`.
    #
    # [1] https://docs.travis-ci.com/user/trusty-ci-environment/
    - os: linux
      sudo: required
      dist: trusty
      compiler: clang
    - os: linux
      sudo: required
      dist: trusty
      compiler: gcc

    # We're not running OS X because we sometimes draw very old machines that
    # that don't support some instructions that we use. See
    # https://github.com/BitFunnel/NativeJIT/issues/53 for discussion.

# Installs libstdc++ 4.9, by installing the GCC 4.9 toolchain. This is required,
# because on Ubuntu Trusty, we need a version  libstdc++ that is compliant to
# C++14. The default toolchain distributed by Trusty is not, hence we must use
# our own.
install:
- if [ "$CXX" = "g++" ]; then export CXX="g++-4.9" CC="gcc-4.9"; fi
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.9
    - g++-4.9
    - clang

# The build scripts.
script:
  - ./Configure_Make.sh
  - cd build-make
  - make -j4
  - make test -j4
